steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - docker build -t southamerica-west1-docker.pkg.dev/store-micro/store-images-registry/order-ms -f dockerfile.prod --platform=linux/amd64 --build-arg $$DATABASE_URL .

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-west1-docker.pkg.dev/store-micro/store-images-registry/order-ms',
    ]

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/987660925856/secrets/orders-db-url/versions/1
    env: 'DATABASE_URL'